### ISSUE TITLE
Configure Springdoc

### ISSUE THREAD

**Issue by josdem** [josdem/status-catcher#2]
**Todo**
As a **user**, I want to integrate [SpringDoc](https://springdoc.org/) **so that** I can have [Open API](https://www.openapis.org/) documentation.

**Acceptance Criteria**
- I have a SpringDoc URL where I can browse endpoints
- I have a link attached in the `readme` file

**Comment by HimanshuGangwarOfficial** [comment]
I can not see any suggested url in readme file.

Default url for swagger-ui is http://localIPhost:8080/webjars/swagger-ui/index.html
If you want to suggest any other url then please let me know.

**Comment by josdem** [comment]
Hi @HimanshuGangwarOfficial, I just completed this issue; please go to the `main` branch; you should see the link there.
